<a href="https://colab.research.google.com/github/CarolyneNjoki72/CarolyneNjoki72/blob/main/00_pytorch_fundamentals_exercises_ipynb_txt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [25]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [26]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [27]:
x.shape, x.ndim , x.device

(torch.Size([7, 7]), 2, device(type='cpu'))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [28]:
# Create another random tensor
y = torch.rand(1, 7)
y.T

# Perform matrix multiplication
torch.matmul(x, y.T)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [29]:
answer_matmul = torch.matmul(x, y.T)
answer_matmul

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [30]:
# Set manual seed
torch.manual_seed(0)

random_tensor_x = torch.rand(7, 7)

torch.manual_seed(0)
random_tensor_y = torch.rand(1, 7)

# Matrix multiply tensors
answer = torch.matmul(random_tensor_x, random_tensor_y.T)
answer, answer.shape


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [37]:
# Set random seed on the GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.cuda.manual_seed(1234)


In [39]:
device

'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [43]:
# Set random seed
torch.cuda.manual_seed(1234)


# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
tensor_A = torch.randn(2, 3).to(device)
tensor_B = torch.randn(2, 3).to(device)
tensor_A,tensor_B

(tensor([[ 1.7179, -0.8507, -0.8486],
         [-0.1848, -1.1938, -0.2233]], device='cuda:0'),
 tensor([[-1.2706,  0.0193,  0.8868],
         [ 0.0552,  0.6880,  1.2326]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [45]:
# Perform matmul on tensor_A and tensor_B
tensor_B.T, tensor_B.T.shape

(tensor([[-1.2706,  0.0552],
         [ 0.0193,  0.6880],
         [ 0.8868,  1.2326]], device='cuda:0'),
 torch.Size([3, 2]))

In [47]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[-2.9518, -1.5366],
         [ 0.0137, -1.1068]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [50]:
# Find max
max_value = torch.max(tensor_C)
max_value


tensor(0.0137, device='cuda:0')

In [51]:
# Find min
min_value = torch.min(tensor_C)
min_value

tensor(-2.9518, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [52]:
# Find arg max
arg_max = torch.argmax(tensor_C)
arg_max



tensor(2, device='cuda:0')

In [53]:
# Find arg min
arg_min = torch.argmin(tensor_C)
arg_min

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [56]:
# Set seed
torch.cuda.manual_seed(7)


# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)
tensor_D, tensor_D.shape






(tensor([[[[0.7967, 0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730,
            0.6186, 0.6962]]]]),
 torch.Size([1, 1, 1, 10]))

In [59]:
# Remove single dimensions
tensor_D_squeezed = tensor_D.squeeze()

# Print out tensors and their shapes
tensor_D_squeezed, tensor_D_squeezed.shape

(tensor([0.7967, 0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186,
         0.6962]),
 torch.Size([10]))